title: My Portfolio
description: This is my portfolio showcasing my projects and skills.
baseurl: "" # leave empty since this is your user page
url: "https://xssVuln.github.io" # replace YOURUSERNAME with your GitHub username
theme: jekyll-theme-hacker # replace “merlot” with your chosen theme from the list
